version: '3.8'
services:
  php-cli:
    build: .
    volumes:
      - .:/home
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mybuh_root_pwd
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    depends_on:
      - rabbitmq3
  rabbitmq3:
    image: rabbitmq:3.8-management
    ports:
      - 80:15672